# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

stages:
  - stage: Test
    jobs:
      - job: Test
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - task: YarnInstaller@3
            inputs:
              versionSpec: '1.x'
              checkLatest: true

          - script: |
              yarn
              yarn lint
              yarn test
            displayName: 'yarn install and test'

  - stage: Deploy
    dependsOn:
      - Test
    condition: and(succeeded('Test'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - task: YarnInstaller@3
            inputs:
              versionSpec: '1.x'
              checkLatest: true
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: $(githubKnownHosts)
              sshPublicKey: $(macroDecoratorsDeployPublic)
              sshKeySecureFile: 'macro-decorators-deploy'

          - script: |
              git config --global user.email "opensource@pzuraq.com";
              git config --global user.name "Chris Garrett";
              git config remote.origin.url "git@github.com:pzuraq/macro-decorators.git"
            displayName: 'Configure Git'

          - script: |
              yarn
              yarn build:docs
              yarn deploy
            displayName: 'Deploy Docs'
